lopf:
  formulations:
    no-ptdf: [angles, cycles, kirchhoff, angles-flows, cycles-flows]
    ptdf: [ptdf, ptdf-flows]
  nos_max:
    no-ptdf: 100
    ptdf: 10
  modes: [p, r, rs15]
  cases: [case118, case300, scigrid, case1354pegase, case1951rte, case2383wp, case2869pegase]
  method: 3
  nhours: 24
sclopf:
  formulations:
    no-ptdf: [angles, cycles, kirchhoff]
    ptdf: []
  nos_max:
    no-ptdf: 10
    ptdf: 0
  modes: [r]
  cases: [case300, case1354pegase] #, scigrid]
  method: 3
  nhours: 24
sclopf-1:
  formulations:
    no-ptdf: [angles, cycles, kirchhoff]
    ptdf: []
  nos_max:
    no-ptdf: 10
    ptdf: 0
  modes: [r]
  cases: [case300, case1354pegase] #, scigrid]
  method: 3
  nhours: 24
lopf-ne:
  formulations:
    no-ptdf: [angles, cycles, angles-flows, kirchhoff, cycles-flows]
    ptdf: []
  nos_max:
    no-ptdf: 100
    ptdf: 0
  modes: [rs15]
  cases: [case118, case300, scigrid, case1354pegase, case1951rte, case2383wp, case2869pegase]
  method: 3
  nhours: 24
lopf-ne-year:
  formulations:
    no-ptdf: [angles, angles-flows, kirchhoff]
    ptdf: []
  nos_max:
    no-ptdf: 1
    ptdf: 0
  modes: 37
  cases: entsoegridkit
  method: 3
  nhours: 2920
types: [sclopf,sclopf-1,lopf-ne]
header: case,mode,nhours,no,formulation,method,N,L,Vars,Constrs,NZs,pVars,pConstrs,pNZs,read_time,presol_time,sol_time,solved_with
